/* eslint-disable @stylistic/indent */
const SITE_DATA = [
    {
        id: 1,
        naam: 'Site 1',
        verantw_id: 1,
    },
    {
        id: 2,
        naam: 'Site 2',
        verantw_id: 2,
    },
    {
        id: 3,
        naam: 'Site 3',
        verantw_id: 3,
    },
];

const MACHINE_DATA = [
    {
        id: 1,
        site_id: 1,
        locatie: 'Locatie 1',
        info: 'Info 1',
        status: 'active',
        prod_status: 'running',
        uptime: 120,
        technieker_id: 1,
        dagenSindsOnderhoud: 10,
        volgendOnderhoud: '2023-11-01T00:00:00Z',
    },
    {
        id: 2,
        site_id: 1,
        locatie: 'Locatie 2',
        info: 'Info 2',
        status: 'inactive',
        prod_status: 'maintenance',
        uptime: 80,
        technieker_id: 2,
        dagenSindsOnderhoud: 20,
        volgendOnderhoud: '2023-11-15T00:00:00Z',
    },
    {
        id: 3,
        site_id: 2,
        locatie: 'Locatie 3',
        info: 'Info 3',
        status: 'active',
        prod_status: 'running',
        uptime: 150,
        technieker_id: 3,
        dagenSindsOnderhoud: 5,
        volgendOnderhoud: '2023-10-25T00:00:00Z',
    },
    {
        id: 4,
        site_id: 2,
        locatie: 'Locatie 4',
        info: 'Info 4',
        status: 'inactive',
        prod_status: 'idle',
        uptime: 60,
        technieker_id: 4,
        dagenSindsOnderhoud: 15,
        volgendOnderhoud: '2023-11-10T00:00:00Z',
    },
    {
        id: 5,
        site_id: 3,
        locatie: 'Locatie 5',
        info: 'Info 5',
        status: 'active',
        prod_status: 'running',
        uptime: 200,
        technieker_id: 5,
        dagenSindsOnderhoud: 3,
        volgendOnderhoud: '2023-10-20T00:00:00Z',
    },
    {
        id: 6,
        site_id: 1,
        locatie: 'Locatie 6',
        info: 'Info 6',
        status: 'inactive',
        prod_status: 'maintenance',
        uptime: 90,
        technieker_id: 6,
        dagenSindsOnderhoud: 25,
        volgendOnderhoud: '2023-11-30T00:00:00Z',
    },
    {
        id: 7,
        site_id: 2,
        locatie: 'Locatie 7',
        info: 'Info 7',
        status: 'active',
        prod_status: 'running',
        uptime: 130,
        technieker_id: 7,
        dagenSindsOnderhoud: 7,
        volgendOnderhoud: '2023-10-28T00:00:00Z',
    },
    {
        id: 8,
        site_id: 3,
        locatie: 'Locatie 8',
        info: 'Info 8',
        status: 'inactive',
        prod_status: 'idle',
        uptime: 50,
        technieker_id: 8,
        dagenSindsOnderhoud: 18,
        volgendOnderhoud: '2023-11-12T00:00:00Z',
    },
    {
        id: 9,
        site_id: 1,
        locatie: 'Locatie 9',
        info: 'Info 9',
        status: 'active',
        prod_status: 'running',
        uptime: 170,
        technieker_id: 9,
        dagenSindsOnderhoud: 2,
        volgendOnderhoud: '2023-10-18T00:00:00Z',
    },
    {
        id: 10,
        site_id: 2,
        locatie: 'Locatie 10',
        info: 'Info 10',
        status: 'inactive',
        prod_status: 'maintenance',
        uptime: 75,
        technieker_id: 10,
        dagenSindsOnderhoud: 22,
        volgendOnderhoud: '2023-11-25T00:00:00Z',
    },
    {
        id: 11,
        site_id: 3,
        locatie: 'Locatie 11',
        info: 'Info 11',
        status: 'active',
        prod_status: 'running',
        uptime: 140,
        technieker_id: 11,
        dagenSindsOnderhoud: 6,
        volgendOnderhoud: '2023-10-27T00:00:00Z',
    },
    {
        id: 12,
        site_id: 1,
        locatie: 'Locatie 12',
        info: 'Info 12',
        status: 'inactive',
        prod_status: 'idle',
        uptime: 65,
        technieker_id: 12,
        dagenSindsOnderhoud: 19,
        volgendOnderhoud: '2023-11-14T00:00:00Z',
    },
    {
        id: 13,
        site_id: 2,
        locatie: 'Locatie 13',
        info: 'Info 13',
        status: 'active',
        prod_status: 'running',
        uptime: 180,
        technieker_id: 13,
        dagenSindsOnderhoud: 1,
        volgendOnderhoud: '2023-10-17T00:00:00Z',
    },
    {
        id: 14,
        site_id: 3,
        locatie: 'Locatie 14',
        info: 'Info 14',
        status: 'inactive',
        prod_status: 'maintenance',
        uptime: 85,
        technieker_id: 14,
        dagenSindsOnderhoud: 23,
        volgendOnderhoud: '2023-11-28T00:00:00Z',
    },
    {
        id: 15,
        site_id: 1,
        locatie: 'Locatie 15',
        info: 'Info 15',
        status: 'active',
        prod_status: 'running',
        uptime: 160,
        technieker_id: 15,
        dagenSindsOnderhoud: 4,
        volgendOnderhoud: '2023-10-22T00:00:00Z',
    },
    {
        id: 16,
        site_id: 2,
        locatie: 'Locatie 16',
        info: 'Info 16',
        status: 'inactive',
        prod_status: 'idle',
        uptime: 55,
        technieker_id: 16,
        dagenSindsOnderhoud: 17,
        volgendOnderhoud: '2023-11-11T00:00:00Z',
    },
    {
        id: 17,
        site_id: 3,
        locatie: 'Locatie 17',
        info: 'Info 17',
        status: 'active',
        prod_status: 'running',
        uptime: 190,
        technieker_id: 17,
        dagenSindsOnderhoud: 0,
        volgendOnderhoud: '2023-10-16T00:00:00Z',
    },
    {
        id: 18,
        site_id: 1,
        locatie: 'Locatie 18',
        info: 'Info 18',
        status: 'inactive',
        prod_status: 'maintenance',
        uptime: 95,
        technieker_id: 18,
        dagenSindsOnderhoud: 21,
        volgendOnderhoud: '2023-11-24T00:00:00Z',
    },
    {
        id: 19,
        site_id: 2,
        locatie: 'Locatie 19',
        info: 'Info 19',
        status: 'active',
        prod_status: 'running',
        uptime: 145,
        technieker_id: 19,
        dagenSindsOnderhoud: 8,
        volgendOnderhoud: '2023-10-29T00:00:00Z',
    },
    {
        id: 20,
        site_id: 3,
        locatie: 'Locatie 20',
        info: 'Info 20',
        status: 'inactive',
        prod_status: 'idle',
        uptime: 70,
        technieker_id: 20,
        dagenSindsOnderhoud: 16,
        volgendOnderhoud: '2023-11-13T00:00:00Z',
    },
];

const MELDING_DATA = [
    {
        id: 1,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-01',
        state: 'ongelezen',
    },
    {
        id: 2,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-02',
        state: 'gelezen',
    },
    {
        id: 3,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-03',
        state: 'nieuw',
    },
    {
        id: 4,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-04',
        state: 'ongelezen',
    },
    {
        id: 5,
        beschrijving: 'Machine 5 is idle',
        type: 'machine',
        datum: '2023-10-05',
        state: 'gelezen',
    },
    {
        id: 6,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-06',
        state: 'nieuw',
    },
    {
        id: 7,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-07',
        state: 'ongelezen',
    },
    {
        id: 8,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-08',
        state: 'gelezen',
    },
    {
        id: 9,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-09',
        state: 'nieuw',
    },
    {
        id: 10,
        beschrijving: 'Machine 5 is idle',
        type: 'machine',
        datum: '2023-10-10',
        state: 'ongelezen',
    },
    {
        id: 11,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-11',
        state: 'gelezen',
    },
    {
        id: 12,
        beschrijving: 'Nieuwe software update beschikbaar voor machine 1 die bestaat uit nieuwe onderdelen',
        type: 'software',
        datum: '2023-10-12',
        state: 'nieuw',
    },
    {
        id: 13,
        beschrijving: 'Machine 2 is terug opgestart',
        type: 'machine',
        datum: '2023-10-13',
        state: 'ongelezen',
    },
    {
        id: 14,
        beschrijving: 'maintenance gepland voor Machine 3',
        type: 'maintenance',
        datum: '2023-10-14',
        state: 'gelezen',
    },
    {
        id: 15,
        beschrijving: 'Nieuwe veiligheidsrichtlijnen',
        type: 'veiligheid',
        datum: '2023-10-15',
        state: 'nieuw',
    },
];

const KPI_DATA = [
    {
        id: 1,
        user_id: 1,
        type: 'line',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 2,
        user_id: 1,
        type: 'bar',
        title: 'Fake Marph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 3,
        user_id: 1,
        type: 'pie',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 4,
        user_id: 1,
        type: 'line',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: false,
    },
];

const ONDERHOUD_DATA = [
    {
      id: 1,
      machine_id: 1,
      datum: '2021-10-01',
      onderhoud_type: 'Grote onderhoud',
      status: 'Voltooid',
      opmerking: 'Geen opmerkingen',
    },
    {
      id: 2,
      machine_id: 2,
      datum: '2021-10-02',
      onderhoud_type: 'Klein onderhoud',
      status: 'Voltooid',
      opmerking: 'Geen opmerkingen',
    },
    {
      id: 3,
      machine_id: 3,
      datum: '2021-10-03',
      onderhoud_type: 'Grote onderhoud',
      status: 'Voltooid',
      opmerking: 'Geen opmerkingen',
    },
  ];

export { SITE_DATA, MACHINE_DATA, MELDING_DATA, KPI_DATA, ONDERHOUD_DATA };