/* eslint-disable @stylistic/indent */
const SITE_DATA = [
    {
        id: 1,
        name: 'Site 1',
        manager: 'Manager 1',
        address: 'Address 1',
    },
    {
        id: 2,
        name: 'Site 2',
        manager: 'Manager 2',
        address: 'Address 2',
    },
    {
        id: 3,
        name: 'Site 3',
        manager: 'Manager 3',
        address: 'Address 3',
    },
];

const MACHINE_DATA = [
    {
        id: 1,
        site_id: 1,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 2,
        site_id: 1,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
    {
        id: 3,
        site_id: 2,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 4,
        site_id: 2,
        status: 'stopped',
        prod_status: 'defect',
    },
    {
        id: 5,
        site_id: 3,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 6,
        site_id: 3,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
    {
        id: 7,
        site_id: 1,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 8,
        site_id: 2,
        status: 'stopped',
        prod_status: 'defect',
    },
    {
        id: 9,
        site_id: 3,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 10,
        site_id: 1,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
    {
        id: 11,
        site_id: 1,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 12,
        site_id: 2,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
    {
        id: 13,
        site_id: 3,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 14,
        site_id: 1,
        status: 'stopped',
        prod_status: 'defect',
    },
    {
        id: 15,
        site_id: 2,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 16,
        site_id: 3,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
    {
        id: 17,
        site_id: 1,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 18,
        site_id: 2,
        status: 'stopped',
        prod_status: 'defect',
    },
    {
        id: 19,
        site_id: 3,
        status: 'running',
        prod_status: 'gezond',
    },
    {
        id: 20,
        site_id: 1,
        status: 'stopped',
        prod_status: 'onderhoud',
    },
];

const MELDING_DATA = [
    {
        id: 1,
        beschrijving: 'Machine 1 is defect',
        type: 'machine',
        datum: '2023-10-01',
        state: 'ongelezen',
    },
    {
        id: 2,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-02',
        state: 'gelezen',
    },
    {
        id: 3,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-03',
        state: 'nieuw',
    },
    {
        id: 4,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-04',
        state: 'ongelezen',
    },
    {
        id: 5,
        beschrijving: 'Machine 5 is defect',
        type: 'machine',
        datum: '2023-10-05',
        state: 'gelezen',
    },
    {
        id: 6,
        beschrijving: 'Machine 1 is defect',
        type: 'machine',
        datum: '2023-10-06',
        state: 'nieuw',
    },
    {
        id: 7,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-07',
        state: 'ongelezen',
    },
    {
        id: 8,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-08',
        state: 'gelezen',
    },
    {
        id: 9,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-09',
        state: 'nieuw',
    },
    {
        id: 10,
        beschrijving: 'Machine 5 is defect',
        type: 'machine',
        datum: '2023-10-10',
        state: 'ongelezen',
    },
    {
        id: 11,
        beschrijving: 'Machine 1 is defect',
        type: 'machine',
        datum: '2023-10-11',
        state: 'gelezen',
    },
    {
        id: 12,
        beschrijving: 'Nieuwe software update beschikbaar voor machine 1 die bestaat uit nieuwe onderdelen',
        type: 'software',
        datum: '2023-10-12',
        state: 'nieuw',
    },
    {
        id: 13,
        beschrijving: 'Machine 2 is terug opgestart',
        type: 'machine',
        datum: '2023-10-13',
        state: 'ongelezen',
    },
    {
        id: 14,
        beschrijving: 'Onderhoud gepland voor Machine 3',
        type: 'onderhoud',
        datum: '2023-10-14',
        state: 'gelezen',
    },
    {
        id: 15,
        beschrijving: 'Nieuwe veiligheidsrichtlijnen',
        type: 'veiligheid',
        datum: '2023-10-15',
        state: 'nieuw',
    },
];

export { SITE_DATA, MACHINE_DATA, MELDING_DATA };