/* eslint-disable @stylistic/indent */
const SITE_DATA = [
    {
        id: 1,
        name: 'Site 1',
        manager: 'Manager 1',
        address: 'Address 1',
    },
    {
        id: 2,
        name: 'Site 2',
        manager: 'Manager 2',
        address: 'Address 2',
    },
    {
        id: 3,
        name: 'Site 3',
        manager: 'Manager 3',
        address: 'Address 3',
    },
];

const MACHINE_DATA = [
    {
        id: 1,
        site_id: 1,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 2,
        site_id: 1,
        state: 'inactive',
        prod_state: 'maintenance',
    },
    {
        id: 3,
        site_id: 2,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 4,
        site_id: 2,
        state: 'inactive',
        prod_state: 'idle',
    },
    {
        id: 5,
        site_id: 3,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 6,
        site_id: 3,
        state: 'inactive',
        prod_state: 'maintenance',
    },
    {
        id: 7,
        site_id: 1,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 8,
        site_id: 2,
        state: 'inactive',
        prod_state: 'idle',
    },
    {
        id: 9,
        site_id: 3,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 10,
        site_id: 1,
        state: 'inactive',
        prod_state: 'maintenance',
    },
    {
        id: 11,
        site_id: 1,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 12,
        site_id: 2,
        state: 'inactive',
        prod_state: 'maintenance',
    },
    {
        id: 13,
        site_id: 3,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 14,
        site_id: 1,
        state: 'inactive',
        prod_state: 'idle',
    },
    {
        id: 15,
        site_id: 2,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 16,
        site_id: 3,
        state: 'inactive',
        prod_state: 'maintenance',
    },
    {
        id: 17,
        site_id: 1,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 18,
        site_id: 2,
        state: 'inactive',
        prod_state: 'idle',
    },
    {
        id: 19,
        site_id: 3,
        state: 'active',
        prod_state: 'running',
    },
    {
        id: 20,
        site_id: 1,
        state: 'inactive',
        prod_state: 'maintenance',
    },
];

const MELDING_DATA = [
    {
        id: 1,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-01',
        state: 'ongelezen',
    },
    {
        id: 2,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-02',
        state: 'gelezen',
    },
    {
        id: 3,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-03',
        state: 'nieuw',
    },
    {
        id: 4,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-04',
        state: 'ongelezen',
    },
    {
        id: 5,
        beschrijving: 'Machine 5 is idle',
        type: 'machine',
        datum: '2023-10-05',
        state: 'gelezen',
    },
    {
        id: 6,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-06',
        state: 'nieuw',
    },
    {
        id: 7,
        beschrijving: 'Je bent verplaatstt naar een andere site',
        type: 'site',
        datum: '2023-10-07',
        state: 'ongelezen',
    },
    {
        id: 8,
        beschrijving: 'Machine 4 is terug opgestart',
        type: 'machine',
        datum: '2023-10-08',
        state: 'gelezen',
    },
    {
        id: 9,
        beschrijving: 'Een KPI is overschreden',
        type: 'kpi',
        datum: '2023-10-09',
        state: 'nieuw',
    },
    {
        id: 10,
        beschrijving: 'Machine 5 is idle',
        type: 'machine',
        datum: '2023-10-10',
        state: 'ongelezen',
    },
    {
        id: 11,
        beschrijving: 'Machine 1 is idle',
        type: 'machine',
        datum: '2023-10-11',
        state: 'gelezen',
    },
    {
        id: 12,
        beschrijving: 'Nieuwe software update beschikbaar voor machine 1 die bestaat uit nieuwe onderdelen',
        type: 'software',
        datum: '2023-10-12',
        state: 'nieuw',
    },
    {
        id: 13,
        beschrijving: 'Machine 2 is terug opgestart',
        type: 'machine',
        datum: '2023-10-13',
        state: 'ongelezen',
    },
    {
        id: 14,
        beschrijving: 'maintenance gepland voor Machine 3',
        type: 'maintenance',
        datum: '2023-10-14',
        state: 'gelezen',
    },
    {
        id: 15,
        beschrijving: 'Nieuwe veiligheidsrichtlijnen',
        type: 'veiligheid',
        datum: '2023-10-15',
        state: 'nieuw',
    },
];

const KPI_DATA = [
    {
        id: 1,
        user_id: 1,
        type: 'line',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 2,
        user_id: 1,
        type: 'bar',
        title: 'Fake Marph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 3,
        user_id: 1,
        type: 'pie',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: true,
    },
    {
        id: 4,
        user_id: 1,
        type: 'line',
        title: 'Fake Graph',
        data: [
            { name: 'Jan', uv: 400, pv: 2400, amt: 2400 },
            { name: 'Feb', uv: 300, pv: 1398, amt: 2210 },
            { name: 'Mar', uv: 200, pv: 9800, amt: 2290 },
            { name: 'Apr', uv: 278, pv: 3908, amt: 2000 },
            { name: 'May', uv: 189, pv: 4800, amt: 2181 },
            { name: 'Jun', uv: 239, pv: 3800, amt: 2500 },
            { name: 'Jul', uv: 349, pv: 4300, amt: 2100 },
        ],
        onDashboard: false,
    },
];

export { SITE_DATA, MACHINE_DATA, MELDING_DATA, KPI_DATA };